/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day28_assingment;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Student st = new Student();
        st.setId(100);
        st.setName("test");

        StudImpl ob;
        ob = new StudImpl();
        ob.update(st);
        ob.delete(st);
        ob.insert(st);
        ob.select(st);
        ob.getStud(100);

    }
}
